In [408]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from collections import defaultdict

In [409]:
class SISA:
    def __init__(self, shards = 5, slices = 5) -> None:
        self.shards = shards
        self.slices = slices
        self.models = [DecisionTreeClassifier() for _ in range(self.shards)]
    
    def train(self, x : np.ndarray, y : np.ndarray) -> None:
        self.input_shards = np.array_split(x, self.shards)
        self.output_shards = np.array_split(y, self.shards)

        for i, model in enumerate(self.models):
            model.fit(self.input_shards[i], self.output_shards[i])
    
    def predict(self, x : np.ndarray) -> None:
        prediction_results = []
        for current_data in x:
            current_pred = 0
            final_pred = 0
            freq = defaultdict(int)

            for model in self.models:
                current_pred = model.predict([current_data])[0]
                freq[current_pred] += 1

                if freq[current_pred] > freq[final_pred]:
                    final_pred = current_pred
                
            prediction_results.append(final_pred)
        
        return np.array(prediction_results)

    def delete(self, x:np.ndarray) -> None:
        nsi = self.input_shards.copy()
        nso = self.output_shards.copy()
        for data in x:
            for i, shard in enumerate(nsi):
                for j, element in enumerate(shard):
                    if np.array_equal(data, element):
                        nsi[i] = np.delete(nsi[i], j, axis= 0)
                        nso[i] = np.delete(nso[i], j)
                        break
        
        for i in range(len(nsi)):
            if len(self.input_shards[i]) != len(nsi[i]):
                print(f"dilakukan retrain pada shard {i}")
                self.models[i].fit(nsi[i], nso[i])
                self.input_shards[i] = nsi[i]
                self.output_shards[i] = nso[i]
    
if __name__ == "__main__":
    testing = SISA()
    print(testing.models)


[DecisionTreeClassifier(), DecisionTreeClassifier(), DecisionTreeClassifier(), DecisionTreeClassifier(), DecisionTreeClassifier()]


In [410]:
data = pd.read_csv("cleaned_loan.csv")
data

Pekerjaan                                     Jenis Pinjaman  \
0     KARYAWAN         PEMBELIAN BEKAS / SECONDARY, RUMAH TINGGAL   
1    PENGUSAHA         PEMBELIAN BEKAS / SECONDARY, RUMAH TINGGAL   
2     KARYAWAN              TAKE OVER + TOP UP KPR, RUMAH TINGGAL   
3    PENGUSAHA         PEMBELIAN BEKAS / SECONDARY, RUMAH TINGGAL   
4     KARYAWAN         PEMBELIAN BEKAS / SECONDARY, RUMAH TINGGAL   
..         ...                                                ...   
195   KARYAWAN  Pembelian Baru / Primary, Rumah Tinggal > Tipe 70   
196   KARYAWAN  Pembelian Baru / Primary, Rumah Tinggal Tipe 2...   
197   KARYAWAN  Pembelian Baru / Primary, Rumah Tinggal Tipe 2...   
198  PENGUSAHA             Pembelian Baru / Primary, Ruko / Rukan   
199   KARYAWAN   Pembelian Baru / Primary, Apartemen Tipe 22 - 70   

                             Plafon (Rp.) Kondisi Joint Income  \
0                  Plafon (< 514,750,000)   TIDAK JOINT INCOME   
1                Plafon (> 1,340,960,436)   TIDAK JOINT INCOME   
2                Plafon (> 1,340,960,436)         JOINT INCOME   
3    Plafon (894,632,536 - 1,340,960,436)         JOINT INCOME   
4                  Plafon (< 514,750,000)         JOINT INCOME   
..                                    ...                  ...   
195              Plafon (> 1,340,960,436)   TIDAK JOINT INCOME   
196                Plafon (< 514,750,000)         JOINT INCOME   
197                Plafon (< 514,750,000)   TIDAK JOINT INCOME   
198              Plafon (> 1,340,960,436)   TIDAK JOINT INCOME   
199    Plafon (514,750,000 - 894,632,536)   TIDAK JOINT INCOME   

    Kondisi Pisah Harta     Usia            Hasil IDEB SLIK OJK  \
0     TIDAK PISAH HARTA  21 - 35            Data Tidak Tersedia   
1           PISAH HARTA  36 - 45  Kol 1, Tidak pernah menunggak   
2     TIDAK PISAH HARTA  46 - 55  Kol 1, Tidak pernah menunggak   
3     TIDAK PISAH HARTA  36 - 45  Kol 1, Tidak pernah menunggak   
4     TIDAK PISAH HARTA  21 - 35            Data Tidak Tersedia   
..                  ...      ...                            ...   
195   TIDAK PISAH HARTA  21 - 35  Kol 1, Tidak pernah menunggak   
196   TIDAK PISAH HARTA  21 - 35            Data Tidak Tersedia   
197   TIDAK PISAH HARTA  21 - 35  Kol 1, Tidak pernah menunggak   
198         PISAH HARTA  56 - 65  Kol 1, Tidak pernah menunggak   
199   TIDAK PISAH HARTA  46 - 55  Kol 1, Tidak pernah menunggak   

        Tujuan Pemilikan Properti Lama bekerja  \
0      Rumah Tinggal (Rumah ke 1)     ≥ 2, < 5   
1      Rumah Tinggal (Rumah ke 1)          ≥ 5   
2      Rumah Tinggal (Rumah ke 1)          ≥ 5   
3    RUMAH TINGGAL (RUMAH KE 2/3)          ≥ 5   
4      Rumah Tinggal (Rumah ke 1)     ≥ 2, < 5   
..                            ...          ...   
195    Rumah Tinggal (Rumah ke 1)     ≥ 2, < 5   
196    Rumah Tinggal (Rumah ke 1)          ≥ 5   
197    Rumah Tinggal (Rumah ke 1)     ≥ 2, < 5   
198    Rumah Tinggal (Rumah ke 1)          ≥ 5   
199    Rumah Tinggal (Rumah ke 1)          ≥ 5   

                             Penghasilan  ... Down Payment   \
0                   SINGLE : ≥RP 10 JUTA  ...        >= 15%   
1                  MENIKAH : ≥RP 20 JUTA  ...        >= 15%   
2                  MENIKAH : ≥RP 20 JUTA  ...        >= 15%   
3                  MENIKAH : ≥RP 20 JUTA  ...        >= 15%   
4     SINGLE : ≥RP 6 JUTA, < RP. 10 JUTA  ...        >= 15%   
..                                   ...  ...           ...   
195                 SINGLE : ≥RP 20 JUTA  ...        >= 15%   
196  MENIKAH : ≥RP 10 JUTA,  <RP 20 JUTA  ...        >= 15%   
197   SINGLE : ≥RP 6 JUTA, < RP. 10 JUTA  ...        >= 15%   
198                MENIKAH : ≥RP 20 JUTA  ...        >= 15%   
199                 SINGLE : ≥RP 20 JUTA  ...        >= 15%   

                Asset lainnya yang dimiliki  \
0        DEPOSITO/INVES/EMAS ≥ LIMIT KREDIT   
1        DEPOSITO/INVES/EMAS ≥ LIMIT KREDIT   
2         PROPERTI/KENDARAAN ≥ LIMIT KREDIT   
3    PROPERTI/KENDARAAN < 100% L

In [411]:
labelEncoder = {}
for col in data.columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    labelEncoder[col] = le

In [412]:
X = data.drop(["Keputusan Akhir"], axis=1)
y = data["Keputusan Akhir"]

In [413]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [414]:
print(X_train.values)

[[1 1 3 ... 1 0 0]
 [0 7 2 ... 0 2 1]
 [0 1 2 ... 1 0 0]
 ...
 [0 6 1 ... 0 2 0]
 [0 7 0 ... 0 1 1]
 [1 7 3 ... 0 0 0]]


In [415]:
print(y_train.values)

[0 1 0 1 0 1 1 1 0 1 0 1 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 1 0 1 0 1 0 0 0 1
 0 0 0 0 0 0 1 1 0 1 0 1 1 1 0 0 1 1 1 1 0 1 0 0 1 0 0 0 0 1 1 0 0 1 0 1 1
 0 0 1 0 1 1 0 0 1 1 1 1 1 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1 1 0 0 1 0 0 1 0 1
 1 0 0 1 1 1 0 1 0 1 0 1 1 1 1 0 0 1 1 0 0 1 1 1 1 0 0 1 1 0 1 0 0 1 0 1 0
 0 0 0 1 1 1 0 0 1 1 1 0]


In [416]:
sisa_classifier = SISA(3,5)

In [417]:
sisa_classifier.train(X_train.values, y_train.values)

In [418]:
print("Akurasi Model SISA: ", accuracy_score(sisa_classifier.predict(X_test.values), y_test))

Akurasi Model SISA:  0.925


In [419]:
data_hapus = X_train.values[0].copy()
data_hapus

array([ 1,  1,  3,  1,  0,  1,  8,  2,  2,  3,  1,  2,  3,  1,  1,  9, 23,
        0,  6,  2,  1,  0,  0])

In [420]:
flag = 0
for i in range(len(sisa_classifier.input_shards[0])):
    if np.array_equal(sisa_classifier.input_shards[0][i], data_hapus):
        flag= 1
if flag ==0 :
    print("yess berhasil")
else:
    print("percobaan gagal")

percobaan gagal


In [421]:
sisa_classifier.delete([X_train.values[0]])

dilakukan retrain pada shard 0


In [422]:
flag = 0
for i in range(len(sisa_classifier.input_shards[0])):
    if np.array_equal(sisa_classifier.input_shards[0][i], data_hapus):
        flag= 1
if flag ==0 :
    print("yess berhasil")
else:
    print("percobaan gagal")

yess berhasil
