In [19]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from collections import defaultdict
import xgboost as xgb

In [20]:
class SISA:
    def __init__(self, shards = 5, slices = 5) -> None:
        self.shards = shards
        self.slices = slices
        self.models = [xgb.XGBClassifier(use_label_encoder=False, eval_metric='mlogloss') for _ in range(self.shards)]
    
    def train(self, x : np.ndarray, y : np.ndarray) -> None:
        self.input_shards = np.array_split(x, self.shards)
        self.output_shards = np.array_split(y, self.shards)

        for i, model in enumerate(self.models):
            model.fit(self.input_shards[i], self.output_shards[i])
    
    def predict(self, x : np.ndarray) -> None:
        prediction_results = []
        for current_data in x:
            current_pred = 0
            final_pred = 0
            freq = defaultdict(int)

            for model in self.models:
                current_pred = model.predict([current_data])[0]
                freq[current_pred] += 1

                if freq[current_pred] > freq[final_pred]:
                    final_pred = current_pred
                
            prediction_results.append(final_pred)
        
        return np.array(prediction_results)

    def delete(self, x:np.ndarray) -> None:
        nsi = self.input_shards.copy()
        nso = self.output_shards.copy()
        for data in x:
            for i, shard in enumerate(nsi):
                for j, element in enumerate(shard):
                    if np.array_equal(data, element):
                        nsi[i] = np.delete(nsi[i], j, axis= 0)
                        nso[i] = np.delete(nso[i], j)
                        break
        
        for i in range(len(nsi)):
            if len(self.input_shards[i]) != len(nsi[i]):
                print(f"dilakukan retrain pada shard {i}")
                self.models[i].fit(nsi[i], nso[i])
                self.input_shards[i] = nsi[i]
                self.output_shards[i] = nso[i]
    
if __name__ == "__main__":
    testing = SISA()
    print(testing.models)


[XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, random_state=None, ...), XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=F

In [21]:
data = pd.read_csv("cleaned_loan.csv")
data

Pekerjaan                                     Jenis Pinjaman  \
0     KARYAWAN         PEMBELIAN BEKAS / SECONDARY, RUMAH TINGGAL   
1    PENGUSAHA         PEMBELIAN BEKAS / SECONDARY, RUMAH TINGGAL   
2     KARYAWAN              TAKE OVER + TOP UP KPR, RUMAH TINGGAL   
3    PENGUSAHA         PEMBELIAN BEKAS / SECONDARY, RUMAH TINGGAL   
4     KARYAWAN         PEMBELIAN BEKAS / SECONDARY, RUMAH TINGGAL   
..         ...                                                ...   
195   KARYAWAN  Pembelian Baru / Primary, Rumah Tinggal > Tipe 70   
196   KARYAWAN  Pembelian Baru / Primary, Rumah Tinggal Tipe 2...   
197   KARYAWAN  Pembelian Baru / Primary, Rumah Tinggal Tipe 2...   
198  PENGUSAHA             Pembelian Baru / Primary, Ruko / Rukan   
199   KARYAWAN   Pembelian Baru / Primary, Apartemen Tipe 22 - 70   

                             Plafon (Rp.) Kondisi Joint Income  \
0                  Plafon (< 514,750,000)   TIDAK JOINT INCOME   
1                Plafon (> 1,340,960,436)   TIDAK JOINT INCOME   
2                Plafon (> 1,340,960,436)         JOINT INCOME   
3    Plafon (894,632,536 - 1,340,960,436)         JOINT INCOME   
4                  Plafon (< 514,750,000)         JOINT INCOME   
..                                    ...                  ...   
195              Plafon (> 1,340,960,436)   TIDAK JOINT INCOME   
196                Plafon (< 514,750,000)         JOINT INCOME   
197                Plafon (< 514,750,000)   TIDAK JOINT INCOME   
198              Plafon (> 1,340,960,436)   TIDAK JOINT INCOME   
199    Plafon (514,750,000 - 894,632,536)   TIDAK JOINT INCOME   

    Kondisi Pisah Harta     Usia            Hasil IDEB SLIK OJK  \
0     TIDAK PISAH HARTA  21 - 35            Data Tidak Tersedia   
1           PISAH HARTA  36 - 45  Kol 1, Tidak pernah menunggak   
2     TIDAK PISAH HARTA  46 - 55  Kol 1, Tidak pernah menunggak   
3     TIDAK PISAH HARTA  36 - 45  Kol 1, Tidak pernah menunggak   
4     TIDAK PISAH HARTA  21 - 35            Data Tidak Tersedia   
..                  ...      ...                            ...   
195   TIDAK PISAH HARTA  21 - 35  Kol 1, Tidak pernah menunggak   
196   TIDAK PISAH HARTA  21 - 35            Data Tidak Tersedia   
197   TIDAK PISAH HARTA  21 - 35  Kol 1, Tidak pernah menunggak   
198         PISAH HARTA  56 - 65  Kol 1, Tidak pernah menunggak   
199   TIDAK PISAH HARTA  46 - 55  Kol 1, Tidak pernah menunggak   

        Tujuan Pemilikan Properti Lama bekerja  \
0      Rumah Tinggal (Rumah ke 1)     ≥ 2, < 5   
1      Rumah Tinggal (Rumah ke 1)          ≥ 5   
2      Rumah Tinggal (Rumah ke 1)          ≥ 5   
3    RUMAH TINGGAL (RUMAH KE 2/3)          ≥ 5   
4      Rumah Tinggal (Rumah ke 1)     ≥ 2, < 5   
..                            ...          ...   
195    Rumah Tinggal (Rumah ke 1)     ≥ 2, < 5   
196    Rumah Tinggal (Rumah ke 1)          ≥ 5   
197    Rumah Tinggal (Rumah ke 1)     ≥ 2, < 5   
198    Rumah Tinggal (Rumah ke 1)          ≥ 5   
199    Rumah Tinggal (Rumah ke 1)          ≥ 5   

                             Penghasilan  ... Down Payment   \
0                   SINGLE : ≥RP 10 JUTA  ...        >= 15%   
1                  MENIKAH : ≥RP 20 JUTA  ...        >= 15%   
2                  MENIKAH : ≥RP 20 JUTA  ...        >= 15%   
3                  MENIKAH : ≥RP 20 JUTA  ...        >= 15%   
4     SINGLE : ≥RP 6 JUTA, < RP. 10 JUTA  ...        >= 15%   
..                                   ...  ...           ...   
195                 SINGLE : ≥RP 20 JUTA  ...        >= 15%   
196  MENIKAH : ≥RP 10 JUTA,  <RP 20 JUTA  ...        >= 15%   
197   SINGLE : ≥RP 6 JUTA, < RP. 10 JUTA  ...        >= 15%   
198                MENIKAH : ≥RP 20 JUTA  ...        >= 15%   
199                 SINGLE : ≥RP 20 JUTA  ...        >= 15%   

                Asset lainnya yang dimiliki  \
0        DEPOSITO/INVES/EMAS ≥ LIMIT KREDIT   
1        DEPOSITO/INVES/EMAS ≥ LIMIT KREDIT   
2         PROPERTI/KENDARAAN ≥ LIMIT KREDIT   
3    PROPERTI/KENDARAAN < 100% L

In [22]:
labelEncoder = {}
for col in data.columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    labelEncoder[col] = le

In [23]:
X = data.drop(["Keputusan Akhir"], axis=1)
y = data["Keputusan Akhir"]

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [25]:
print(X_train.values)

[[1 1 3 ... 1 0 0]
 [0 7 2 ... 0 2 1]
 [0 1 2 ... 1 0 0]
 ...
 [0 6 1 ... 0 2 0]
 [0 7 0 ... 0 1 1]
 [1 7 3 ... 0 0 0]]


In [26]:
print(y_train.values)

[0 1 0 1 0 1 1 1 0 1 0 1 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 1 0 1 0 1 0 0 0 1
 0 0 0 0 0 0 1 1 0 1 0 1 1 1 0 0 1 1 1 1 0 1 0 0 1 0 0 0 0 1 1 0 0 1 0 1 1
 0 0 1 0 1 1 0 0 1 1 1 1 1 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1 1 0 0 1 0 0 1 0 1
 1 0 0 1 1 1 0 1 0 1 0 1 1 1 1 0 0 1 1 0 0 1 1 1 1 0 0 1 1 0 1 0 0 1 0 1 0
 0 0 0 1 1 1 0 0 1 1 1 0]


In [27]:
sisa_classifier = SISA(3,5)

In [28]:
sisa_classifier.train(X_train.values, y_train.values)

In [29]:
print("Akurasi Model SISA: ", accuracy_score(sisa_classifier.predict(X_test.values), y_test))

Akurasi Model SISA:  0.875


In [30]:
exp_results = pd.DataFrame(columns=['Shard', 'Accuracy'])
exp_results

Empty DataFrame
Columns: [Shard, Accuracy]
Index: []

In [31]:
shard = 2
accuracy = 1
while accuracy > 0.6:
    sisa_classifier = SISA(shard, 5)
    sisa_classifier.train(X_train.values, y_train.values)
    y_pred = sisa_classifier.predict(X_test.values)
    accuracy = accuracy_score(y_pred, y_test)
    exp_results = pd.concat([exp_results, pd.DataFrame([{'Shard': shard, 'Accuracy': accuracy}])], ignore_index=True)
    shard += 1

In [32]:
data_result = pd.DataFrame(exp_results)
data_result

Shard  Accuracy
0      2     0.950
1      3     0.875
2      4     0.925
3      5     0.950
4      6     0.975
5      7     0.950
6      8     0.950
7      9     0.975
8     10     0.975
9     11     0.975
10    12     0.975
11    13     0.950
12    14     0.975
13    15     0.975
14    16     0.750
15    17     0.675
16    18     0.475

In [33]:
# data_hapus = X_train.values[0].copy()
# data_hapus

In [34]:
# flag = 0
# for i in range(len(sisa_classifier.input_shards[0])):
#     if np.array_equal(sisa_classifier.input_shards[0][i], data_hapus):
#         flag= 1
# if flag ==0 :
#     print("yess berhasil")
# else:
#     print("percobaan gagal")

In [35]:
# sisa_classifier.delete([X_train.values[0]])

In [36]:
# flag = 0
# for i in range(len(sisa_classifier.input_shards[0])):
#     if np.array_equal(sisa_classifier.input_shards[0][i], data_hapus):
#         flag= 1
# if flag ==0 :
#     print("yess berhasil")
# else:
#     print("percobaan gagal")